# Generated by Django 4.1.3 on 2022-11-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('img1', models.ImageField(upload_to='pics1')),
                ('desc1', models.TextField()),
            ],
        ),
    ]
